### ISSUE TITLE
Adding Zigbee lib as a component

### ISSUE THREAD

**Issue by lbernstone** [espressif/esp32-arduino-lib-builder#142]
Please add [zigbee](https://components.espressif.com/components/espressif/esp-zboss-lib) and [zboss](https://components.espressif.com/components/espressif/esp-zboss-lib) as components.  These have variant-specific pre-built library archives, so will be very difficult to integrate otherwise.

**Comment by VojtechBartoska** [comment]
Hi, @P-R-O-C-H-Y is now working on that.

Here is related issue in the core, https://github.com/espressif/arduino-esp32/issues/8807

**Comment by me-no-dev** [comment]
> These have variant-specific pre-built library archives, so will be very difficult to integrate otherwise.

also complicated to do here :D

**Comment by VojtechBartoska** [comment]
@P-R-O-C-H-Y can we close this in favor of https://github.com/espressif/esp32-arduino-lib-builder/pull/146 and https://github.com/espressif/arduino-esp32/pull/8844?

**Comment by lbernstone** [comment]
Good job, @P-R-O-C-H-Y
