### ISSUE TITLE
inconsistent setting for: `CONFIG_SPIRAM_TRY_ALLOCATE_WIFI_LWIP=y`

### ISSUE THREAD

**Issue by Jason2866** [espressif/esp32-arduino-lib-builder#162]
@me-no-dev this option is set for esp32-s2 and esp32-s3 and it is not set for the esp32.
Is this intended or just forgotten to set for the esp32?

**Comment by me-no-dev** [comment]
because there are some issues with older ESP32 chips, I would rather have this OFF for vanilla ESP32

**Comment by Jason2866** [comment]
Thx, for the info.
