### ISSUE TITLE
ULP not included for S2 & S3

### ISSUE THREAD

**Issue by lbernstone** [espressif/esp32-arduino-lib-builder#173]
S2 & S3 need `CONFIG_ULP_COPROC_TYPE_FSM=y` & `CONFIG_ULP_COPROC_TYPE_RISCV=y` set in their sdkconfig so that the ulp libraries are available.
C6 & P4 need `CONFIG_ULP_COPROC_TYPE_LP_CORE=y`
Fixes https://github.com/espressif/arduino-esp32/issues/9579

**Comment by me-no-dev** [comment]
can you test it if we provide the libs?

**Comment by lbernstone** [comment]
Sorry for the delay.  I will test this ASAP.  LP-core is still not enabled for C6 (CONFIG_ULP_COPROC_TYPE_LP_CORE=y). There is a request at https://github.com/espressif/arduino-esp32/issues/9721
