### ISSUE TITLE
Build failure when using docker container

### ISSUE THREAD

**Issue by mskvortsov** [espressif/esp32-arduino-lib-builder#201]
```
docker run --rm -it -v $PWD/output:/arduino-esp32 \
  espressif/esp32-arduino-lib-builder:latest ./build.sh -t esp32
```
```
CMake Error at esp-idf/tools/cmake/build.cmake:540 (message):
  ERROR: Some components (espressif/esp-dsp) in the "managed_components"
  directory were modified on the disk since the last run of the CMake.
  Content of this directory is managed automatically.
```
[failure.log](https://github.com/user-attachments/files/16580899/failure.log)

**Comment by me-no-dev** [comment]
nothing else should be required. CI runs this every 6 hours with success.

@lucasssvaz PTAL

**Comment by lucasssvaz** [comment]
Started happening on master as well https://github.com/espressif/esp32-arduino-lib-builder/actions/runs/10369405267/job/28705079316

**Comment by lucasssvaz** [comment]
Idk if something changed in IDF

**Comment by me-no-dev** [comment]
@lucasssvaz maybe we can try with older version of DSP

**Comment by lucasssvaz** [comment]
> @lucasssvaz maybe we can try with older version of DSP

Let me test

**Comment by lucasssvaz** [comment]
Yup, does not work even with older versions

**Comment by Jason2866** [comment]
issue is solved in actual Arduino Lib Builder

**Comment by mskvortsov** [comment]
It builds now, thank you.
