### ISSUE TITLE
Compilation not working

### ISSUE THREAD

**Issue by SIMONPrCoder** [espressif/esp32-arduino-lib-builder#202]
I'm trying to compile the libraries with SPP disabled. I installed python both 32bit and 64bit version and all the other stuff.
When I press Compile Static Libraries I always get the same error regardless of what Python Version I use (3.12.5).
`error = OSError(8, '%1 ist keine zulässige Win32-Anwendung', None, 193, None)`

**Comment by me-no-dev** [comment]
@lucasssvaz PTAL
