### ISSUE TITLE
Package release doesnt contain some chips anymore

### ISSUE THREAD

**Issue by maxgerhardt** [espressif/esp32-arduino-lib-builder#215]
From https://raw.githubusercontent.com/espressif/arduino-esp32/master/package/package_esp32_index.template.json taking the URL 

```
          "version": "idf-release_v5.1-e026fd1f",
          "systems": [
            {
              "host": "i686-mingw32",
              "url": "https://github.com/espressif/esp32-arduino-lib-builder/releases/download/idf-release_v5.1/esp32-arduino-libs-idf-release_v5.1-e026fd1f.zip",
```
has the content

![grafik](https://github.com/user-attachments/assets/3d9405fa-9c2c-40ad-8fb2-5226a6175c04)

ESP32C2 is missing in action? How's that possible?

**Comment by maxgerhardt** [comment]
My bad, see README of Arduino-ESP32. Got confused by build errors in CI complaining about the esp32c2 folder not existing.

**Comment by orangeagain** [comment]
so, where is it?

**Comment by me-no-dev** [comment]
C2 is not part of our regular builds. If you want support, you need to compile the libs yourself or use Arduino as IDF component.
