### ISSUE TITLE
Question: git pull branch instead of checkout? 

### ISSUE THREAD

**Issue by alorbach** [espressif/esp32-arduino-lib-builder#22]
Is there any specific reason why the update scripts are using git pull instead of git checkout "branch"?
When switching between branches, git pull causes a lot of unsolveable conflicts. 

https://github.com/espressif/esp32-arduino-lib-builder/blob/b86ba2bb50e2b1b0e55d7a530fffa228b5c2d841/tools/update-components.sh#L13

https://github.com/espressif/esp32-arduino-lib-builder/blob/b86ba2bb50e2b1b0e55d7a530fffa228b5c2d841/tools/install-esp-idf.sh#L96

**Comment by me-no-dev** [comment]
what is your use case? it uses pull so that the latest sources are pulled and updated, not so much for switching branches.

**Comment by alorbach** [comment]
I think git pull is ok if you want to merge changes from one branch to another. 
Perhaps it should be changed 

`git -C "$AR_COMPS/arduino" checkout master && git pull `

`git -C $IDF_PATH fetch origin && git -C $IDF_PATH checkout $IDF_BRANCH && git pull origin`

For example when you switch from esp-idf 3.2 to 3.3 and back, you won't accidentally merge changes between both branches. 

FYI, I just noticed that the tools script also switched to git checkout in branch v4.2.

**Comment by me-no-dev** [comment]
4.2 will become master very soon :) feel free to PR any changes you want to master now

**Comment by alorbach** [comment]
I may create a PR later ok ;),
I will start looking into 4,2 now, if that's the new master soon :)
