### ISSUE TITLE
How to compile the libraries with debug info?

### ISSUE THREAD

**Issue by jsmith173** [espressif/esp32-arduino-lib-builder#238]
### Checklist

- [X] Checked the issue tracker for similar issues to ensure this is not a duplicate.
- [X] Provided a clear description of your suggestion.
- [X] Included any relevant context or examples.

### Issue or Suggestion Description

How to compile the libraries with debug info? (gcc option -Og -g)

**Comment by lucasssvaz** [comment]
AFAIK the libs already contain the debug symbols. @me-no-dev might know better.

**Comment by jsmith173** [comment]
ok
