### ISSUE TITLE
how to recompile libesp32.a ?

### ISSUE THREAD

**Issue by sonolive** [espressif/esp32-arduino-lib-builder#58]
hello,
i have done all the "rebuild" of esp32-arduino, everything is ok ... except the libesp32.a that is not recompiled ...

any way what i am looking for is :
in which lib the "SPI RAM config" from menuconfig is hard coded ?
i need a new config with :
CONFIG_SPIRAM_USE_MEMMAP =y

but as default it is on
CONFIG_SPIRAM_USE_MALLOC=y

maybe it is not hard coded in libesp32.a, but if not, where ? in what lib ?

many thanx in advance

**Comment by me-no-dev** [comment]
Anything starting with `CONFIG_` is in `sdkconfig`. You need to adjust the sdkconfig for the particular chip, then run `./build.sh` and then copy the files in the output folder, like it's done in `./tools/copy-to-arduino.sh`. If you want to know where certain define is used, then you can grep ESP-IDF :)
