### ISSUE TITLE
ESP32 header fields too long for server to interpret

### ISSUE THREAD

**Issue by Patsjemoe** [espressif/esp32-arduino-lib-builder#74]
Hi,
This issue has been on GIthub before for a long time, but I still see no solution.
I was using Firefox, so could get around it.
But now I am using Webview in Android Studio, and have again the problem of headers too long.
Changing the HTTPD_MAX value in sdkconfig does not solve the issue.
Is there a "real" solution in the mean time ?
thanks in advance
best regards
Ludo

**Comment by me-no-dev** [comment]
Do you have any idea how large are the headers? Did you recompile the libs after changing the value in sdkconfig?

**Comment by Patsjemoe** [comment]
Hi,
Thank you for your quick reply.
I recompile the program, so I assume this takes the new file. Do you need
to recompile the libraries separately? If so, how?
Regards
Ludo

Op wo 6 jul. 2022 09:56 schreef Me No Dev ***@***.***>:

**Comment by me-no-dev** [comment]
Which version of ESP32-Arduino are you using?

https://docs.espressif.com/projects/arduino-esp32/en/latest/lib_builder.html

**Comment by Patsjemoe** [comment]
Hi,
I am using arduino 1.8.19
Regards
Ludo

Op wo 6 jul. 2022 10:38 schreef Me No Dev ***@***.***>:

**Comment by me-no-dev** [comment]
> I am using arduino 1.8.19

This is the IDE version. I am asking about the ESP32-Arduino version. Something like 1.0.6, 2.0.3 etc.

> I had the impression all these files were downloaded, so how can I include the sdkconfig with my changes ?

You change [this file here](https://github.com/espressif/esp32-arduino-lib-builder/blob/master/configs/defconfig.common#L42) and then compile and copy the libs

**Comment by Patsjemoe** [comment]
Where do I find that?

Op wo 6 jul. 2022 11:28 schreef Me No Dev ***@***.***>:

**Comment by Patsjemoe** [comment]
Hi,
I found : tags/2.0.4-0-gc93bf11f
THis is in c:/windows/syswow64/esp32-lib-builder.
Can you confirm which libs to copy ? Is this
esp32-arduino-lib-builder/components/arduino/libraries ?
regards
Ludo

**Comment by Patsjemoe** [comment]
Hi,
Is there a document /tutorial on the lib builder ?
Specifically , it is not clear to me on how/what to compile in which
directory, and to get the right files to arduino IDE.
Regards
Ludo

**Comment by Patsjemoe** [comment]
Hi Me No Dev,
is ./tools/copy-to-arduino.sh copying to the installed arduino IDE ?
regards
Ludo

**Comment by Patsjemoe** [comment]
Hi,
when I look into this file copy-to-arduino.sh, I see only the ESP32_ARDUINO
directory, and do not find anything
that copies it to the IDE installation. What am I missing ?
regards
Ludo

**Comment by me-no-dev** [comment]
are you looking at the script or the result of running it? It is becoming really hard to help you now.

**Comment by Patsjemoe** [comment]
Hi,
I was looking to the script, as it is not clear to me where the result is
copied to.
It is also not clear to me what the result is, and how I can get this to my
arduino IDE ?
regards
Ludo

**Comment by me-no-dev** [comment]
I think that this conversation is going out of topic :) You wanted to change a value and test it, but now we are into explaining what each script does. The script will detect your OS and select the proper folder for your arduino-esp32 install (which you should have done from github into your sketches/hardware folder). I hope this is enough for you to actually try what I have been asking...
