### ISSUE TITLE
when build to ./build.sh, appear "./build.sh: line 139: jq: command not found"

### ISSUE THREAD

**Issue by hyu7000** [espressif/esp32-arduino-lib-builder#96]
I was following the install process. [AA](https://espressif-docs.readthedocs-hosted.com/projects/arduino-esp32/en/latest/lib_builder.html)

at last step, some error(?) appear. in tools dir, there is not sdk dir.

stdout is not a tty
./build.sh: line 139: jq: command not found

![image](https://user-images.githubusercontent.com/82933946/202858778-42bc3c93-8728-4be4-9f0e-5a0f9c5768fa.png)

how to resolve error?

thank you

**Comment by hamishcunningham** [comment]
`sudo apt install jq`
should do the trick if you're on Linux?

**Comment by hyu7000** [comment]
@hamishcunningham 
i use Window.
should i build it only Linux or Pi?

**Comment by hamishcunningham** [comment]
A command ending ".sh" is for a unix type shell, so you need to find the
equivalent ".bat" or similar, or use Linux or an emulator or vm or....

**Comment by hyu7000** [comment]
@hamishcunningham 
thank you, i will try ubuntu
